# Generated by Django 3.2 on 2021-04-22 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0002_auto_20210422_1702'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tweet',
            old_name='owner',
            new_name='author',
        ),
    ]
